version: "3"
services:
  app:
    build: ./app # Ruta al directorio de la aplicación web
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - mongodb

  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=database_nahir

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mysql-data:
  mongodb-data:
